[package]
name         = "signal-terminal"
version      = "0.3.0"
edition      = "2024"
rust-version = "1.89"
license      = "MIT OR Apache-2.0"
repository   = "https://github.com/LiGoldragon/signal-terminal"
description  = "Signal contract for Persona terminal transport control."
publish      = false
links        = "signal-terminal"
build        = "build.rs"

[lib]
name = "signal_terminal"
path = "src/lib.rs"

[features]
default = ["dotos-text"]
dotos-text = ["dep:dotos", "signal-frame/dotos-text"]

[dependencies]
dotos         = { package = "dotos", git = "https://github.com/LiGoldragon/dotos.git", rev = "80c7b17f7ad3cf547d2624c6a243e5de5f85c9f3", optional = true }
rkyv         = { version = "0.8", default-features = false, features = ["std", "bytecheck", "little_endian", "pointer_width_32", "unaligned"] }
signal-frame = { git = "https://github.com/LiGoldragon/signal-frame.git", rev = "ca72b2d1151f5b3df536295b2ba68f039536ec19", default-features = false }
thiserror    = "2"

[build-dependencies]
protos = { git = "https://github.com/LiGoldragon/protos.git", rev = "9bce5ed8efadeb157811b256aa69a1f88cd5314f" }
schema = { git = "https://github.com/LiGoldragon/schema.git", rev = "c966e0ce30bbc53c809941cf462b7b6447fff185" }
schema-rust = { package = "schema-rust", git = "https://github.com/LiGoldragon/schema-rust.git", rev = "6179a7cf1394083244dd3f3e1d2709f9ec08f7db" }

[lints.rust]
unsafe_code = "forbid"
unused      = { level = "warn", priority = -1 }
dead_code   = "warn"
