// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecode, NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalName(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalGeneration(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalSequence(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalByteCount(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalRows(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalColumns(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalInputBytes(Vec<Integer>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalTranscriptBytes(Vec<Integer>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PromptPatternIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PromptPatternBytes(Vec<Integer>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InputGateReason(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InputGateLeaseIdentifier(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WirePath(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SocketMode(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SystemPrincipal(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnixUserIdentifier(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ExitCode(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalSignalNumber(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WorkerFailureDetail(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum OwnerIdentity {
    UnixUser(UnixUserIdentifier),
    System(SystemPrincipal),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum TerminalDetachmentReason {
    HumanRequested,
    HarnessStopped,
    ViewerReplaced,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum TerminalRejectionReason {
    NotConnected,
    InputRejected,
    ResizeRejected,
    CaptureRejected,
    TransportFailed,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InjectionRejectionReason {
    UnknownTerminal,
    UnknownLease,
    GateNotHeld,
    DirtyPrompt,
    TransportFailed,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum TerminalExitStatus {
    Exited(ExitCode),
    Signaled(TerminalSignalNumber),
    StatusUnavailable,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum PromptPattern {
    LiteralSuffix(PromptPatternBytes),
    RegexSuffix(PromptPatternBytes),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum PromptState {
    NotChecked,
    Clean,
    Dirty(TerminalByteCount),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InputGateLease(InputGateLeaseIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum TerminalWorkerKind {
    InputWriter,
    ViewerFanout,
    TranscriptScriber,
    OutputReader,
    ChildExitWatcher,
    SocketAcceptLoop,
    AttachConnectionPump,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum TerminalWorkerStopReason {
    InputCommandChannelClosed,
    InputWriteFailed(WorkerFailureDetail),
    OutputCommandChannelClosed,
    TranscriptNoticeChannelClosed,
    OutputReaderFinished,
    OutputReadFailed(WorkerFailureDetail),
    OutputPortClosed,
    ChildExited(WorkerFailureDetail),
    ChildWaitFailed(WorkerFailureDetail),
    SocketAcceptFailed(WorkerFailureDetail),
    AttachConnectionClosed,
    AttachConnectionFailed(WorkerFailureDetail),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalWorkerStop {
    pub worker: TerminalWorkerKind,
    pub reason: TerminalWorkerStopReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum TerminalWorkerLifecycle {
    Started(TerminalWorkerKind),
    Stopped(TerminalWorkerStop),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum TerminalOperationKind {
    TerminalConnection,
    TerminalInput,
    TerminalResize,
    TerminalDetachment,
    TerminalCapture,
    RegisterPromptPattern,
    UnregisterPromptPattern,
    ListPromptPatterns,
    AcquireInputGate,
    ReleaseInputGate,
    WriteInjection,
    SubscribeTerminalWorkerLifecycle,
    TerminalWorkerLifecycleRetraction,
    ListSessions,
    ResolveSession,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalConnection(TerminalName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalInput {
    pub terminal: TerminalName,
    pub bytes: TerminalInputBytes,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalResize {
    pub terminal: TerminalName,
    pub rows: TerminalRows,
    pub columns: TerminalColumns,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalDetachment {
    pub terminal: TerminalName,
    pub reason: TerminalDetachmentReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalCapture(TerminalName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RegisterPromptPattern {
    pub terminal: TerminalName,
    pub pattern: PromptPattern,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnregisterPromptPattern {
    pub terminal: TerminalName,
    pub pattern_id: PromptPatternIdentifier,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ListPromptPatterns(TerminalName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AcquireInputGate {
    pub terminal: TerminalName,
    pub reason: InputGateReason,
    pub prompt_pattern_identifier: Option<PromptPatternIdentifier>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReleaseInputGate {
    pub terminal: TerminalName,
    pub lease: InputGateLease,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WriteInjection {
    pub terminal: TerminalName,
    pub lease: InputGateLease,
    pub bytes: TerminalInputBytes,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubscribeTerminalWorkerLifecycle(TerminalName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalWorkerLifecycleToken(TerminalName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ListSessions {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ResolveSession(TerminalName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalReady {
    pub terminal: TerminalName,
    pub generation: TerminalGeneration,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalInputAccepted {
    pub terminal: TerminalName,
    pub generation: TerminalGeneration,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TranscriptDelta {
    pub terminal: TerminalName,
    pub sequence: TerminalSequence,
    pub bytes: TerminalTranscriptBytes,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalResized {
    pub terminal: TerminalName,
    pub rows: TerminalRows,
    pub columns: TerminalColumns,
    pub generation: TerminalGeneration,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalCaptured {
    pub terminal: TerminalName,
    pub generation: TerminalGeneration,
    pub bytes: TerminalTranscriptBytes,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalDetached {
    pub terminal: TerminalName,
    pub generation: TerminalGeneration,
    pub reason: TerminalDetachmentReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalExited {
    pub terminal: TerminalName,
    pub generation: TerminalGeneration,
    pub status: TerminalExitStatus,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalRejected {
    pub terminal: TerminalName,
    pub reason: TerminalRejectionReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PromptPatternRegistered {
    pub terminal: TerminalName,
    pub pattern_id: PromptPatternIdentifier,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PromptPatternUnregistered {
    pub terminal: TerminalName,
    pub pattern_id: PromptPatternIdentifier,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PromptPatternEntry {
    pub pattern_id: PromptPatternIdentifier,
    pub pattern: PromptPattern,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PromptPatternList {
    pub terminal: TerminalName,
    pub entries: Vec<PromptPatternEntry>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GateAcquired {
    pub terminal: TerminalName,
    pub lease: InputGateLease,
    pub prompt_state: PromptState,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GateBusy {
    pub terminal: TerminalName,
    pub current_holder: InputGateLeaseIdentifier,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GateReleased {
    pub terminal: TerminalName,
    pub lease: InputGateLease,
    pub cached_human_bytes: TerminalByteCount,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InjectionAck {
    pub terminal: TerminalName,
    pub generation: TerminalGeneration,
    pub sequence: TerminalSequence,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InjectionRejected {
    pub terminal: TerminalName,
    pub reason: InjectionRejectionReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalWorkerLifecycleSnapshot {
    pub terminal: TerminalName,
    pub observations: Vec<TerminalWorkerLifecycle>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalWorkerLifecycleEvent {
    pub terminal: TerminalName,
    pub observation: TerminalWorkerLifecycle,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubscriptionRetracted(TerminalWorkerLifecycleToken);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SessionEntry {
    pub name: TerminalName,
    pub data_socket_path: WirePath,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SessionList(Vec<SessionEntry>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SessionResolved {
    pub name: TerminalName,
    pub data_socket_path: WirePath,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum TerminalEvent {
    TerminalWorkerLifecycleEvent(TerminalWorkerLifecycleEvent),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalDaemonConfiguration {
    pub terminal_socket_path: WirePath,
    pub terminal_socket_mode: SocketMode,
    pub meta_terminal_socket_path: WirePath,
    pub meta_terminal_socket_mode: SocketMode,
    pub supervision_socket_path: WirePath,
    pub supervision_socket_mode: SocketMode,
    pub store_path: WirePath,
    pub owner_identity: OwnerIdentity,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    TerminalConnection(TerminalConnection),
    TerminalInput(TerminalInput),
    TerminalResize(TerminalResize),
    TerminalDetachment(TerminalDetachment),
    TerminalCapture(TerminalCapture),
    RegisterPromptPattern(RegisterPromptPattern),
    UnregisterPromptPattern(UnregisterPromptPattern),
    ListPromptPatterns(ListPromptPatterns),
    AcquireInputGate(AcquireInputGate),
    ReleaseInputGate(ReleaseInputGate),
    WriteInjection(WriteInjection),
    SubscribeTerminalWorkerLifecycle(SubscribeTerminalWorkerLifecycle),
    TerminalWorkerLifecycleRetraction(TerminalWorkerLifecycleToken),
    ListSessions(ListSessions),
    ResolveSession(ResolveSession),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    TerminalReady(TerminalReady),
    TerminalInputAccepted(TerminalInputAccepted),
    TranscriptDelta(TranscriptDelta),
    TerminalResized(TerminalResized),
    TerminalCaptured(TerminalCaptured),
    TerminalDetached(TerminalDetached),
    TerminalExited(TerminalExited),
    TerminalRejected(TerminalRejected),
    PromptPatternRegistered(PromptPatternRegistered),
    PromptPatternUnregistered(PromptPatternUnregistered),
    PromptPatternList(PromptPatternList),
    GateAcquired(GateAcquired),
    GateBusy(GateBusy),
    GateReleased(GateReleased),
    InjectionAck(InjectionAck),
    InjectionRejected(InjectionRejected),
    TerminalWorkerLifecycleSnapshot(TerminalWorkerLifecycleSnapshot),
    SubscriptionRetracted(SubscriptionRetracted),
    SessionList(SessionList),
    SessionResolved(SessionResolved),
    Event(TerminalEvent),
}

#[rustfmt::skip]
impl TerminalName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for TerminalName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TerminalGeneration {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for TerminalGeneration {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TerminalSequence {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for TerminalSequence {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TerminalByteCount {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for TerminalByteCount {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TerminalRows {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for TerminalRows {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TerminalColumns {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for TerminalColumns {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TerminalInputBytes {
    pub fn new(payload: Vec<Integer>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<Integer> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<Integer> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<Integer>> for TerminalInputBytes {
    fn from(payload: Vec<Integer>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TerminalTranscriptBytes {
    pub fn new(payload: Vec<Integer>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<Integer> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<Integer> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<Integer>> for TerminalTranscriptBytes {
    fn from(payload: Vec<Integer>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PromptPatternIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for PromptPatternIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PromptPatternBytes {
    pub fn new(payload: Vec<Integer>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<Integer> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<Integer> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<Integer>> for PromptPatternBytes {
    fn from(payload: Vec<Integer>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl InputGateReason {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for InputGateReason {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl InputGateLeaseIdentifier {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for InputGateLeaseIdentifier {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WirePath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for WirePath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SocketMode {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for SocketMode {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SystemPrincipal {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for SystemPrincipal {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UnixUserIdentifier {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for UnixUserIdentifier {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ExitCode {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for ExitCode {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TerminalSignalNumber {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for TerminalSignalNumber {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WorkerFailureDetail {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for WorkerFailureDetail {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl InputGateLease {
    pub fn new(payload: InputGateLeaseIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &InputGateLeaseIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> InputGateLeaseIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<InputGateLeaseIdentifier> for InputGateLease {
    fn from(payload: InputGateLeaseIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TerminalConnection {
    pub fn new(payload: TerminalName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TerminalName {
        &self.0
    }
    pub fn into_payload(self) -> TerminalName {
        self.0
    }
}
#[rustfmt::skip]
impl From<TerminalName> for TerminalConnection {
    fn from(payload: TerminalName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TerminalCapture {
    pub fn new(payload: TerminalName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TerminalName {
        &self.0
    }
    pub fn into_payload(self) -> TerminalName {
        self.0
    }
}
#[rustfmt::skip]
impl From<TerminalName> for TerminalCapture {
    fn from(payload: TerminalName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ListPromptPatterns {
    pub fn new(payload: TerminalName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TerminalName {
        &self.0
    }
    pub fn into_payload(self) -> TerminalName {
        self.0
    }
}
#[rustfmt::skip]
impl From<TerminalName> for ListPromptPatterns {
    fn from(payload: TerminalName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SubscribeTerminalWorkerLifecycle {
    pub fn new(payload: TerminalName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TerminalName {
        &self.0
    }
    pub fn into_payload(self) -> TerminalName {
        self.0
    }
}
#[rustfmt::skip]
impl From<TerminalName> for SubscribeTerminalWorkerLifecycle {
    fn from(payload: TerminalName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TerminalWorkerLifecycleToken {
    pub fn new(payload: TerminalName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TerminalName {
        &self.0
    }
    pub fn into_payload(self) -> TerminalName {
        self.0
    }
}
#[rustfmt::skip]
impl From<TerminalName> for TerminalWorkerLifecycleToken {
    fn from(payload: TerminalName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ResolveSession {
    pub fn new(payload: TerminalName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TerminalName {
        &self.0
    }
    pub fn into_payload(self) -> TerminalName {
        self.0
    }
}
#[rustfmt::skip]
impl From<TerminalName> for ResolveSession {
    fn from(payload: TerminalName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SubscriptionRetracted {
    pub fn new(payload: TerminalWorkerLifecycleToken) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TerminalWorkerLifecycleToken {
        &self.0
    }
    pub fn into_payload(self) -> TerminalWorkerLifecycleToken {
        self.0
    }
}
#[rustfmt::skip]
impl From<TerminalWorkerLifecycleToken> for SubscriptionRetracted {
    fn from(payload: TerminalWorkerLifecycleToken) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SessionList {
    pub fn new(payload: Vec<SessionEntry>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<SessionEntry> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<SessionEntry> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<SessionEntry>> for SessionList {
    fn from(payload: Vec<SessionEntry>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl OwnerIdentity {
    pub fn unix_user(payload: Integer) -> Self {
        Self::UnixUser(UnixUserIdentifier::new(payload))
    }
    pub fn system(payload: String) -> Self {
        Self::System(SystemPrincipal::new(payload))
    }
}

#[rustfmt::skip]
impl TerminalExitStatus {
    pub fn exited(payload: Integer) -> Self {
        Self::Exited(ExitCode::new(payload))
    }
    pub fn signaled(payload: Integer) -> Self {
        Self::Signaled(TerminalSignalNumber::new(payload))
    }
}

#[rustfmt::skip]
impl PromptPattern {
    pub fn literal_suffix(payload: Vec<Integer>) -> Self {
        Self::LiteralSuffix(PromptPatternBytes::new(payload))
    }
    pub fn regex_suffix(payload: Vec<Integer>) -> Self {
        Self::RegexSuffix(PromptPatternBytes::new(payload))
    }
}

#[rustfmt::skip]
impl PromptState {
    pub fn dirty(payload: Integer) -> Self {
        Self::Dirty(TerminalByteCount::new(payload))
    }
}

#[rustfmt::skip]
impl TerminalWorkerStopReason {
    pub fn input_write_failed(payload: String) -> Self {
        Self::InputWriteFailed(WorkerFailureDetail::new(payload))
    }
    pub fn output_read_failed(payload: String) -> Self {
        Self::OutputReadFailed(WorkerFailureDetail::new(payload))
    }
    pub fn child_exited(payload: String) -> Self {
        Self::ChildExited(WorkerFailureDetail::new(payload))
    }
    pub fn child_wait_failed(payload: String) -> Self {
        Self::ChildWaitFailed(WorkerFailureDetail::new(payload))
    }
    pub fn socket_accept_failed(payload: String) -> Self {
        Self::SocketAcceptFailed(WorkerFailureDetail::new(payload))
    }
    pub fn attach_connection_failed(payload: String) -> Self {
        Self::AttachConnectionFailed(WorkerFailureDetail::new(payload))
    }
}

#[rustfmt::skip]
impl TerminalWorkerLifecycle {
    pub fn started(payload: TerminalWorkerKind) -> Self {
        Self::Started(payload)
    }
    pub fn stopped(payload: TerminalWorkerStop) -> Self {
        Self::Stopped(payload)
    }
}

#[rustfmt::skip]
impl TerminalEvent {
    pub fn terminal_worker_lifecycle_event(
        payload: TerminalWorkerLifecycleEvent,
    ) -> Self {
        Self::TerminalWorkerLifecycleEvent(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn terminal_connection(payload: TerminalName) -> Self {
        Self::TerminalConnection(TerminalConnection::new(payload))
    }
    pub fn terminal_input(payload: TerminalInput) -> Self {
        Self::TerminalInput(payload)
    }
    pub fn terminal_resize(payload: TerminalResize) -> Self {
        Self::TerminalResize(payload)
    }
    pub fn terminal_detachment(payload: TerminalDetachment) -> Self {
        Self::TerminalDetachment(payload)
    }
    pub fn terminal_capture(payload: TerminalName) -> Self {
        Self::TerminalCapture(TerminalCapture::new(payload))
    }
    pub fn register_prompt_pattern(payload: RegisterPromptPattern) -> Self {
        Self::RegisterPromptPattern(payload)
    }
    pub fn unregister_prompt_pattern(payload: UnregisterPromptPattern) -> Self {
        Self::UnregisterPromptPattern(payload)
    }
    pub fn list_prompt_patterns(payload: TerminalName) -> Self {
        Self::ListPromptPatterns(ListPromptPatterns::new(payload))
    }
    pub fn acquire_input_gate(payload: AcquireInputGate) -> Self {
        Self::AcquireInputGate(payload)
    }
    pub fn release_input_gate(payload: ReleaseInputGate) -> Self {
        Self::ReleaseInputGate(payload)
    }
    pub fn write_injection(payload: WriteInjection) -> Self {
        Self::WriteInjection(payload)
    }
    pub fn subscribe_terminal_worker_lifecycle(payload: TerminalName) -> Self {
        Self::SubscribeTerminalWorkerLifecycle(
            SubscribeTerminalWorkerLifecycle::new(payload),
        )
    }
    pub fn terminal_worker_lifecycle_retraction(payload: TerminalName) -> Self {
        Self::TerminalWorkerLifecycleRetraction(
            TerminalWorkerLifecycleToken::new(payload),
        )
    }
    pub fn list_sessions(payload: ListSessions) -> Self {
        Self::ListSessions(payload)
    }
    pub fn resolve_session(payload: TerminalName) -> Self {
        Self::ResolveSession(ResolveSession::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn terminal_ready(payload: TerminalReady) -> Self {
        Self::TerminalReady(payload)
    }
    pub fn terminal_input_accepted(payload: TerminalInputAccepted) -> Self {
        Self::TerminalInputAccepted(payload)
    }
    pub fn transcript_delta(payload: TranscriptDelta) -> Self {
        Self::TranscriptDelta(payload)
    }
    pub fn terminal_resized(payload: TerminalResized) -> Self {
        Self::TerminalResized(payload)
    }
    pub fn terminal_captured(payload: TerminalCaptured) -> Self {
        Self::TerminalCaptured(payload)
    }
    pub fn terminal_detached(payload: TerminalDetached) -> Self {
        Self::TerminalDetached(payload)
    }
    pub fn terminal_exited(payload: TerminalExited) -> Self {
        Self::TerminalExited(payload)
    }
    pub fn terminal_rejected(payload: TerminalRejected) -> Self {
        Self::TerminalRejected(payload)
    }
    pub fn prompt_pattern_registered(payload: PromptPatternRegistered) -> Self {
        Self::PromptPatternRegistered(payload)
    }
    pub fn prompt_pattern_unregistered(payload: PromptPatternUnregistered) -> Self {
        Self::PromptPatternUnregistered(payload)
    }
    pub fn prompt_pattern_list(payload: PromptPatternList) -> Self {
        Self::PromptPatternList(payload)
    }
    pub fn gate_acquired(payload: GateAcquired) -> Self {
        Self::GateAcquired(payload)
    }
    pub fn gate_busy(payload: GateBusy) -> Self {
        Self::GateBusy(payload)
    }
    pub fn gate_released(payload: GateReleased) -> Self {
        Self::GateReleased(payload)
    }
    pub fn injection_ack(payload: InjectionAck) -> Self {
        Self::InjectionAck(payload)
    }
    pub fn injection_rejected(payload: InjectionRejected) -> Self {
        Self::InjectionRejected(payload)
    }
    pub fn terminal_worker_lifecycle_snapshot(
        payload: TerminalWorkerLifecycleSnapshot,
    ) -> Self {
        Self::TerminalWorkerLifecycleSnapshot(payload)
    }
    pub fn subscription_retracted(payload: TerminalWorkerLifecycleToken) -> Self {
        Self::SubscriptionRetracted(SubscriptionRetracted::new(payload))
    }
    pub fn session_list(payload: Vec<SessionEntry>) -> Self {
        Self::SessionList(SessionList::new(payload))
    }
    pub fn session_resolved(payload: SessionResolved) -> Self {
        Self::SessionResolved(payload)
    }
    pub fn event(payload: TerminalEvent) -> Self {
        Self::Event(payload)
    }
}

#[rustfmt::skip]
impl From<UnixUserIdentifier> for OwnerIdentity {
    fn from(payload: UnixUserIdentifier) -> Self {
        Self::UnixUser(payload)
    }
}

#[rustfmt::skip]
impl From<SystemPrincipal> for OwnerIdentity {
    fn from(payload: SystemPrincipal) -> Self {
        Self::System(payload)
    }
}

#[rustfmt::skip]
impl From<ExitCode> for TerminalExitStatus {
    fn from(payload: ExitCode) -> Self {
        Self::Exited(payload)
    }
}

#[rustfmt::skip]
impl From<TerminalSignalNumber> for TerminalExitStatus {
    fn from(payload: TerminalSignalNumber) -> Self {
        Self::Signaled(payload)
    }
}

#[rustfmt::skip]
impl From<TerminalByteCount> for PromptState {
    fn from(payload: TerminalByteCount) -> Self {
        Self::Dirty(payload)
    }
}

#[rustfmt::skip]
impl From<TerminalWorkerKind> for TerminalWorkerLifecycle {
    fn from(payload: TerminalWorkerKind) -> Self {
        Self::Started(payload)
    }
}

#[rustfmt::skip]
impl From<TerminalWorkerStop> for TerminalWorkerLifecycle {
    fn from(payload: TerminalWorkerStop) -> Self {
        Self::Stopped(payload)
    }
}

#[rustfmt::skip]
impl From<TerminalWorkerLifecycleEvent> for TerminalEvent {
    fn from(payload: TerminalWorkerLifecycleEvent) -> Self {
        Self::TerminalWorkerLifecycleEvent(payload)
    }
}

#[rustfmt::skip]
impl From<TerminalConnection> for Input {
    fn from(payload: TerminalConnection) -> Self {
        Self::TerminalConnection(payload)
    }
}

#[rustfmt::skip]
impl From<TerminalInput> for Input {
    fn from(payload: TerminalInput) -> Self {
        Self::TerminalInput(payload)
    }
}

#[rustfmt::skip]
impl From<TerminalResize> for Input {
    fn from(payload: TerminalResize) -> Self {
        Self::TerminalResize(payload)
    }
}

#[rustfmt::skip]
impl From<TerminalDetachment> for Input {
    fn from(payload: TerminalDetachment) -> Self {
        Self::TerminalDetachment(payload)
    }
}

#[rustfmt::skip]
impl From<TerminalCapture> for Input {
    fn from(payload: TerminalCapture) -> Self {
        Self::TerminalCapture(payload)
    }
}

#[rustfmt::skip]
impl From<RegisterPromptPattern> for Input {
    fn from(payload: RegisterPromptPattern) -> Self {
        Self::RegisterPromptPattern(payload)
    }
}

#[rustfmt::skip]
impl From<UnregisterPromptPattern> for Input {
    fn from(payload: UnregisterPromptPattern) -> Self {
        Self::UnregisterPromptPattern(payload)
    }
}

#[rustfmt::skip]
impl From<ListPromptPatterns> for Input {
    fn from(payload: ListPromptPatterns) -> Self {
        Self::ListPromptPatterns(payload)
    }
}

#[rustfmt::skip]
impl From<AcquireInputGate> for Input {
    fn from(payload: AcquireInputGate) -> Self {
        Self::AcquireInputGate(payload)
    }
}

#[rustfmt::skip]
impl From<ReleaseInputGate> for Input {
    fn from(payload: ReleaseInputGate) -> Self {
        Self::ReleaseInputGate(payload)
    }
}

#[rustfmt::skip]
impl From<WriteInjection> for Input {
    fn from(payload: WriteInjection) -> Self {
        Self::WriteInjection(payload)
    }
}

#[rustfmt::skip]
impl From<SubscribeTerminalWorkerLifecycle> for Input {
    fn from(payload: SubscribeTerminalWorkerLifecycle) -> Self {
        Self::SubscribeTerminalWorkerLifecycle(payload)
    }
}

#[rustfmt::skip]
impl From<TerminalWorkerLifecycleToken> for Input {
    fn from(payload: TerminalWorkerLifecycleToken) -> Self {
        Self::TerminalWorkerLifecycleRetraction(payload)
    }
}

#[rustfmt::skip]
impl From<ListSessions> for Input {
    fn from(payload: ListSessions) -> Self {
        Self::ListSessions(payload)
    }
}

#[rustfmt::skip]
impl From<ResolveSession> for Input {
    fn from(payload: ResolveSession) -> Self {
        Self::ResolveSession(payload)
    }
}

#[rustfmt::skip]
impl From<TerminalReady> for Output {
    fn from(payload: TerminalReady) -> Self {
        Self::TerminalReady(payload)
    }
}

#[rustfmt::skip]
impl From<TerminalInputAccepted> for Output {
    fn from(payload: TerminalInputAccepted) -> Self {
        Self::TerminalInputAccepted(payload)
    }
}

#[rustfmt::skip]
impl From<TranscriptDelta> for Output {
    fn from(payload: TranscriptDelta) -> Self {
        Self::TranscriptDelta(payload)
    }
}

#[rustfmt::skip]
impl From<TerminalResized> for Output {
    fn from(payload: TerminalResized) -> Self {
        Self::TerminalResized(payload)
    }
}

#[rustfmt::skip]
impl From<TerminalCaptured> for Output {
    fn from(payload: TerminalCaptured) -> Self {
        Self::TerminalCaptured(payload)
    }
}

#[rustfmt::skip]
impl From<TerminalDetached> for Output {
    fn from(payload: TerminalDetached) -> Self {
        Self::TerminalDetached(payload)
    }
}

#[rustfmt::skip]
impl From<TerminalExited> for Output {
    fn from(payload: TerminalExited) -> Self {
        Self::TerminalExited(payload)
    }
}

#[rustfmt::skip]
impl From<TerminalRejected> for Output {
    fn from(payload: TerminalRejected) -> Self {
        Self::TerminalRejected(payload)
    }
}

#[rustfmt::skip]
impl From<PromptPatternRegistered> for Output {
    fn from(payload: PromptPatternRegistered) -> Self {
        Self::PromptPatternRegistered(payload)
    }
}

#[rustfmt::skip]
impl From<PromptPatternUnregistered> for Output {
    fn from(payload: PromptPatternUnregistered) -> Self {
        Self::PromptPatternUnregistered(payload)
    }
}

#[rustfmt::skip]
impl From<PromptPatternList> for Output {
    fn from(payload: PromptPatternList) -> Self {
        Self::PromptPatternList(payload)
    }
}

#[rustfmt::skip]
impl From<GateAcquired> for Output {
    fn from(payload: GateAcquired) -> Self {
        Self::GateAcquired(payload)
    }
}

#[rustfmt::skip]
impl From<GateBusy> for Output {
    fn from(payload: GateBusy) -> Self {
        Self::GateBusy(payload)
    }
}

#[rustfmt::skip]
impl From<GateReleased> for Output {
    fn from(payload: GateReleased) -> Self {
        Self::GateReleased(payload)
    }
}

#[rustfmt::skip]
impl From<InjectionAck> for Output {
    fn from(payload: InjectionAck) -> Self {
        Self::InjectionAck(payload)
    }
}

#[rustfmt::skip]
impl From<InjectionRejected> for Output {
    fn from(payload: InjectionRejected) -> Self {
        Self::InjectionRejected(payload)
    }
}

#[rustfmt::skip]
impl From<TerminalWorkerLifecycleSnapshot> for Output {
    fn from(payload: TerminalWorkerLifecycleSnapshot) -> Self {
        Self::TerminalWorkerLifecycleSnapshot(payload)
    }
}

#[rustfmt::skip]
impl From<SubscriptionRetracted> for Output {
    fn from(payload: SubscriptionRetracted) -> Self {
        Self::SubscriptionRetracted(payload)
    }
}

#[rustfmt::skip]
impl From<SessionList> for Output {
    fn from(payload: SessionList) -> Self {
        Self::SessionList(payload)
    }
}

#[rustfmt::skip]
impl From<SessionResolved> for Output {
    fn from(payload: SessionResolved) -> Self {
        Self::SessionResolved(payload)
    }
}

#[rustfmt::skip]
impl From<TerminalEvent> for Output {
    fn from(payload: TerminalEvent) -> Self {
        Self::Event(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalName {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalGeneration {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalSequence {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalByteCount {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalRows {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalColumns {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalInputBytes {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalTranscriptBytes {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl PromptPatternIdentifier {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl PromptPatternBytes {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl InputGateReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl InputGateLeaseIdentifier {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl WirePath {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SocketMode {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SystemPrincipal {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl UnixUserIdentifier {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ExitCode {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalSignalNumber {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl WorkerFailureDetail {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl OwnerIdentity {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalDetachmentReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalRejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl InjectionRejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalExitStatus {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl PromptPattern {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl PromptState {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl InputGateLease {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalWorkerKind {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalWorkerStopReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalWorkerStop {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalWorkerLifecycle {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalOperationKind {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalConnection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalResize {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalDetachment {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalCapture {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RegisterPromptPattern {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl UnregisterPromptPattern {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ListPromptPatterns {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AcquireInputGate {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ReleaseInputGate {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl WriteInjection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SubscribeTerminalWorkerLifecycle {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalWorkerLifecycleToken {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ListSessions {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ResolveSession {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalReady {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalInputAccepted {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TranscriptDelta {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalResized {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalCaptured {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalDetached {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalExited {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalRejected {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl PromptPatternRegistered {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl PromptPatternUnregistered {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl PromptPatternEntry {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl PromptPatternList {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl GateAcquired {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl GateBusy {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl GateReleased {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl InjectionAck {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl InjectionRejected {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalWorkerLifecycleSnapshot {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalWorkerLifecycleEvent {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SubscriptionRetracted {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SessionEntry {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SessionList {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SessionResolved {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalEvent {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl TerminalDaemonConfiguration {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_TERMINAL_CONNECTION: u64 = 0x0000000000000000;
    pub const INPUT_TERMINAL_INPUT: u64 = 0x0001000000000000;
    pub const INPUT_TERMINAL_RESIZE: u64 = 0x0002000000000000;
    pub const INPUT_TERMINAL_DETACHMENT: u64 = 0x0003000000000000;
    pub const INPUT_TERMINAL_CAPTURE: u64 = 0x0004000000000000;
    pub const INPUT_REGISTER_PROMPT_PATTERN: u64 = 0x0005000000000000;
    pub const INPUT_UNREGISTER_PROMPT_PATTERN: u64 = 0x0006000000000000;
    pub const INPUT_LIST_PROMPT_PATTERNS: u64 = 0x0007000000000000;
    pub const INPUT_ACQUIRE_INPUT_GATE: u64 = 0x0008000000000000;
    pub const INPUT_RELEASE_INPUT_GATE: u64 = 0x0009000000000000;
    pub const INPUT_WRITE_INJECTION: u64 = 0x000A000000000000;
    pub const INPUT_SUBSCRIBE_TERMINAL_WORKER_LIFECYCLE: u64 = 0x000B000000000000;
    pub const INPUT_TERMINAL_WORKER_LIFECYCLE_RETRACTION: u64 = 0x000C000000000000;
    pub const INPUT_LIST_SESSIONS: u64 = 0x000D000000000000;
    pub const INPUT_RESOLVE_SESSION: u64 = 0x000E000000000000;
    pub const OUTPUT_TERMINAL_READY: u64 = 0x0100000000000000;
    pub const OUTPUT_TERMINAL_INPUT_ACCEPTED: u64 = 0x0101000000000000;
    pub const OUTPUT_TRANSCRIPT_DELTA: u64 = 0x0102000000000000;
    pub const OUTPUT_TERMINAL_RESIZED: u64 = 0x0103000000000000;
    pub const OUTPUT_TERMINAL_CAPTURED: u64 = 0x0104000000000000;
    pub const OUTPUT_TERMINAL_DETACHED: u64 = 0x0105000000000000;
    pub const OUTPUT_TERMINAL_EXITED: u64 = 0x0106000000000000;
    pub const OUTPUT_TERMINAL_REJECTED: u64 = 0x0107000000000000;
    pub const OUTPUT_PROMPT_PATTERN_REGISTERED: u64 = 0x0108000000000000;
    pub const OUTPUT_PROMPT_PATTERN_UNREGISTERED: u64 = 0x0109000000000000;
    pub const OUTPUT_PROMPT_PATTERN_LIST: u64 = 0x010A000000000000;
    pub const OUTPUT_GATE_ACQUIRED: u64 = 0x010B000000000000;
    pub const OUTPUT_GATE_BUSY: u64 = 0x010C000000000000;
    pub const OUTPUT_GATE_RELEASED: u64 = 0x010D000000000000;
    pub const OUTPUT_INJECTION_ACK: u64 = 0x010E000000000000;
    pub const OUTPUT_INJECTION_REJECTED: u64 = 0x010F000000000000;
    pub const OUTPUT_TERMINAL_WORKER_LIFECYCLE_SNAPSHOT: u64 = 0x0110000000000000;
    pub const OUTPUT_SUBSCRIPTION_RETRACTED: u64 = 0x0111000000000000;
    pub const OUTPUT_SESSION_LIST: u64 = 0x0112000000000000;
    pub const OUTPUT_SESSION_RESOLVED: u64 = 0x0113000000000000;
    pub const OUTPUT_EVENT: u64 = 0x0114000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    TerminalConnection,
    TerminalInput,
    TerminalResize,
    TerminalDetachment,
    TerminalCapture,
    RegisterPromptPattern,
    UnregisterPromptPattern,
    ListPromptPatterns,
    AcquireInputGate,
    ReleaseInputGate,
    WriteInjection,
    SubscribeTerminalWorkerLifecycle,
    TerminalWorkerLifecycleRetraction,
    ListSessions,
    ResolveSession,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    TerminalReady,
    TerminalInputAccepted,
    TranscriptDelta,
    TerminalResized,
    TerminalCaptured,
    TerminalDetached,
    TerminalExited,
    TerminalRejected,
    PromptPatternRegistered,
    PromptPatternUnregistered,
    PromptPatternList,
    GateAcquired,
    GateBusy,
    GateReleased,
    InjectionAck,
    InjectionRejected,
    TerminalWorkerLifecycleSnapshot,
    SubscriptionRetracted,
    SessionList,
    SessionResolved,
    Event,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::TerminalConnection(_) => InputRoute::TerminalConnection,
            Self::TerminalInput(_) => InputRoute::TerminalInput,
            Self::TerminalResize(_) => InputRoute::TerminalResize,
            Self::TerminalDetachment(_) => InputRoute::TerminalDetachment,
            Self::TerminalCapture(_) => InputRoute::TerminalCapture,
            Self::RegisterPromptPattern(_) => InputRoute::RegisterPromptPattern,
            Self::UnregisterPromptPattern(_) => InputRoute::UnregisterPromptPattern,
            Self::ListPromptPatterns(_) => InputRoute::ListPromptPatterns,
            Self::AcquireInputGate(_) => InputRoute::AcquireInputGate,
            Self::ReleaseInputGate(_) => InputRoute::ReleaseInputGate,
            Self::WriteInjection(_) => InputRoute::WriteInjection,
            Self::SubscribeTerminalWorkerLifecycle(_) => {
                InputRoute::SubscribeTerminalWorkerLifecycle
            }
            Self::TerminalWorkerLifecycleRetraction(_) => {
                InputRoute::TerminalWorkerLifecycleRetraction
            }
            Self::ListSessions(_) => InputRoute::ListSessions,
            Self::ResolveSession(_) => InputRoute::ResolveSession,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::TerminalConnection(_) => short_header::INPUT_TERMINAL_CONNECTION,
            Self::TerminalInput(_) => short_header::INPUT_TERMINAL_INPUT,
            Self::TerminalResize(_) => short_header::INPUT_TERMINAL_RESIZE,
            Self::TerminalDetachment(_) => short_header::INPUT_TERMINAL_DETACHMENT,
            Self::TerminalCapture(_) => short_header::INPUT_TERMINAL_CAPTURE,
            Self::RegisterPromptPattern(_) => short_header::INPUT_REGISTER_PROMPT_PATTERN,
            Self::UnregisterPromptPattern(_) => {
                short_header::INPUT_UNREGISTER_PROMPT_PATTERN
            }
            Self::ListPromptPatterns(_) => short_header::INPUT_LIST_PROMPT_PATTERNS,
            Self::AcquireInputGate(_) => short_header::INPUT_ACQUIRE_INPUT_GATE,
            Self::ReleaseInputGate(_) => short_header::INPUT_RELEASE_INPUT_GATE,
            Self::WriteInjection(_) => short_header::INPUT_WRITE_INJECTION,
            Self::SubscribeTerminalWorkerLifecycle(_) => {
                short_header::INPUT_SUBSCRIBE_TERMINAL_WORKER_LIFECYCLE
            }
            Self::TerminalWorkerLifecycleRetraction(_) => {
                short_header::INPUT_TERMINAL_WORKER_LIFECYCLE_RETRACTION
            }
            Self::ListSessions(_) => short_header::INPUT_LIST_SESSIONS,
            Self::ResolveSession(_) => short_header::INPUT_RESOLVE_SESSION,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_TERMINAL_CONNECTION => Ok(InputRoute::TerminalConnection),
            short_header::INPUT_TERMINAL_INPUT => Ok(InputRoute::TerminalInput),
            short_header::INPUT_TERMINAL_RESIZE => Ok(InputRoute::TerminalResize),
            short_header::INPUT_TERMINAL_DETACHMENT => Ok(InputRoute::TerminalDetachment),
            short_header::INPUT_TERMINAL_CAPTURE => Ok(InputRoute::TerminalCapture),
            short_header::INPUT_REGISTER_PROMPT_PATTERN => {
                Ok(InputRoute::RegisterPromptPattern)
            }
            short_header::INPUT_UNREGISTER_PROMPT_PATTERN => {
                Ok(InputRoute::UnregisterPromptPattern)
            }
            short_header::INPUT_LIST_PROMPT_PATTERNS => {
                Ok(InputRoute::ListPromptPatterns)
            }
            short_header::INPUT_ACQUIRE_INPUT_GATE => Ok(InputRoute::AcquireInputGate),
            short_header::INPUT_RELEASE_INPUT_GATE => Ok(InputRoute::ReleaseInputGate),
            short_header::INPUT_WRITE_INJECTION => Ok(InputRoute::WriteInjection),
            short_header::INPUT_SUBSCRIBE_TERMINAL_WORKER_LIFECYCLE => {
                Ok(InputRoute::SubscribeTerminalWorkerLifecycle)
            }
            short_header::INPUT_TERMINAL_WORKER_LIFECYCLE_RETRACTION => {
                Ok(InputRoute::TerminalWorkerLifecycleRetraction)
            }
            short_header::INPUT_LIST_SESSIONS => Ok(InputRoute::ListSessions),
            short_header::INPUT_RESOLVE_SESSION => Ok(InputRoute::ResolveSession),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::TerminalReady(_) => OutputRoute::TerminalReady,
            Self::TerminalInputAccepted(_) => OutputRoute::TerminalInputAccepted,
            Self::TranscriptDelta(_) => OutputRoute::TranscriptDelta,
            Self::TerminalResized(_) => OutputRoute::TerminalResized,
            Self::TerminalCaptured(_) => OutputRoute::TerminalCaptured,
            Self::TerminalDetached(_) => OutputRoute::TerminalDetached,
            Self::TerminalExited(_) => OutputRoute::TerminalExited,
            Self::TerminalRejected(_) => OutputRoute::TerminalRejected,
            Self::PromptPatternRegistered(_) => OutputRoute::PromptPatternRegistered,
            Self::PromptPatternUnregistered(_) => OutputRoute::PromptPatternUnregistered,
            Self::PromptPatternList(_) => OutputRoute::PromptPatternList,
            Self::GateAcquired(_) => OutputRoute::GateAcquired,
            Self::GateBusy(_) => OutputRoute::GateBusy,
            Self::GateReleased(_) => OutputRoute::GateReleased,
            Self::InjectionAck(_) => OutputRoute::InjectionAck,
            Self::InjectionRejected(_) => OutputRoute::InjectionRejected,
            Self::TerminalWorkerLifecycleSnapshot(_) => {
                OutputRoute::TerminalWorkerLifecycleSnapshot
            }
            Self::SubscriptionRetracted(_) => OutputRoute::SubscriptionRetracted,
            Self::SessionList(_) => OutputRoute::SessionList,
            Self::SessionResolved(_) => OutputRoute::SessionResolved,
            Self::Event(_) => OutputRoute::Event,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::TerminalReady(_) => short_header::OUTPUT_TERMINAL_READY,
            Self::TerminalInputAccepted(_) => {
                short_header::OUTPUT_TERMINAL_INPUT_ACCEPTED
            }
            Self::TranscriptDelta(_) => short_header::OUTPUT_TRANSCRIPT_DELTA,
            Self::TerminalResized(_) => short_header::OUTPUT_TERMINAL_RESIZED,
            Self::TerminalCaptured(_) => short_header::OUTPUT_TERMINAL_CAPTURED,
            Self::TerminalDetached(_) => short_header::OUTPUT_TERMINAL_DETACHED,
            Self::TerminalExited(_) => short_header::OUTPUT_TERMINAL_EXITED,
            Self::TerminalRejected(_) => short_header::OUTPUT_TERMINAL_REJECTED,
            Self::PromptPatternRegistered(_) => {
                short_header::OUTPUT_PROMPT_PATTERN_REGISTERED
            }
            Self::PromptPatternUnregistered(_) => {
                short_header::OUTPUT_PROMPT_PATTERN_UNREGISTERED
            }
            Self::PromptPatternList(_) => short_header::OUTPUT_PROMPT_PATTERN_LIST,
            Self::GateAcquired(_) => short_header::OUTPUT_GATE_ACQUIRED,
            Self::GateBusy(_) => short_header::OUTPUT_GATE_BUSY,
            Self::GateReleased(_) => short_header::OUTPUT_GATE_RELEASED,
            Self::InjectionAck(_) => short_header::OUTPUT_INJECTION_ACK,
            Self::InjectionRejected(_) => short_header::OUTPUT_INJECTION_REJECTED,
            Self::TerminalWorkerLifecycleSnapshot(_) => {
                short_header::OUTPUT_TERMINAL_WORKER_LIFECYCLE_SNAPSHOT
            }
            Self::SubscriptionRetracted(_) => short_header::OUTPUT_SUBSCRIPTION_RETRACTED,
            Self::SessionList(_) => short_header::OUTPUT_SESSION_LIST,
            Self::SessionResolved(_) => short_header::OUTPUT_SESSION_RESOLVED,
            Self::Event(_) => short_header::OUTPUT_EVENT,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_TERMINAL_READY => Ok(OutputRoute::TerminalReady),
            short_header::OUTPUT_TERMINAL_INPUT_ACCEPTED => {
                Ok(OutputRoute::TerminalInputAccepted)
            }
            short_header::OUTPUT_TRANSCRIPT_DELTA => Ok(OutputRoute::TranscriptDelta),
            short_header::OUTPUT_TERMINAL_RESIZED => Ok(OutputRoute::TerminalResized),
            short_header::OUTPUT_TERMINAL_CAPTURED => Ok(OutputRoute::TerminalCaptured),
            short_header::OUTPUT_TERMINAL_DETACHED => Ok(OutputRoute::TerminalDetached),
            short_header::OUTPUT_TERMINAL_EXITED => Ok(OutputRoute::TerminalExited),
            short_header::OUTPUT_TERMINAL_REJECTED => Ok(OutputRoute::TerminalRejected),
            short_header::OUTPUT_PROMPT_PATTERN_REGISTERED => {
                Ok(OutputRoute::PromptPatternRegistered)
            }
            short_header::OUTPUT_PROMPT_PATTERN_UNREGISTERED => {
                Ok(OutputRoute::PromptPatternUnregistered)
            }
            short_header::OUTPUT_PROMPT_PATTERN_LIST => {
                Ok(OutputRoute::PromptPatternList)
            }
            short_header::OUTPUT_GATE_ACQUIRED => Ok(OutputRoute::GateAcquired),
            short_header::OUTPUT_GATE_BUSY => Ok(OutputRoute::GateBusy),
            short_header::OUTPUT_GATE_RELEASED => Ok(OutputRoute::GateReleased),
            short_header::OUTPUT_INJECTION_ACK => Ok(OutputRoute::InjectionAck),
            short_header::OUTPUT_INJECTION_REJECTED => Ok(OutputRoute::InjectionRejected),
            short_header::OUTPUT_TERMINAL_WORKER_LIFECYCLE_SNAPSHOT => {
                Ok(OutputRoute::TerminalWorkerLifecycleSnapshot)
            }
            short_header::OUTPUT_SUBSCRIPTION_RETRACTED => {
                Ok(OutputRoute::SubscriptionRetracted)
            }
            short_header::OUTPUT_SESSION_LIST => Ok(OutputRoute::SessionList),
            short_header::OUTPUT_SESSION_RESOLVED => Ok(OutputRoute::SessionResolved),
            short_header::OUTPUT_EVENT => Ok(OutputRoute::Event),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "TerminalConnection",
        "TerminalInput",
        "TerminalResize",
        "TerminalDetachment",
        "TerminalCapture",
        "RegisterPromptPattern",
        "UnregisterPromptPattern",
        "ListPromptPatterns",
        "AcquireInputGate",
        "ReleaseInputGate",
        "WriteInjection",
        "SubscribeTerminalWorkerLifecycle",
        "TerminalWorkerLifecycleRetraction",
        "ListSessions",
        "ResolveSession",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::StreamingFrame<Input, Output, TerminalEvent>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::StreamingFrameBody<Input, Output, TerminalEvent>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}

#[rustfmt::skip]
impl TerminalEvent {
    pub fn into_subscription_frame(
        self,
        event_identifier: signal_frame::StreamEventIdentifier,
        token: signal_frame::SubscriptionTokenInner,
    ) -> Frame {
        Frame::with_short_header(
            signal_frame::ShortHeader::new(short_header::OUTPUT_EVENT),
            FrameBody::SubscriptionEvent {
                event_identifier,
                token,
                event: self,
            },
        )
    }
}
